"""add_onboarding_profile_fields

Revision ID: 606e755a0a7a
Revises: fcd399d0f95e
Create Date: 2026-08-04 11:45:24.977588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '606e755a0a7a'
down_revision: Union[str, Sequence[str], None] = 'fcd399d0f95e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_results_id'), table_name='interview_results')
    op.drop_index(op.f('ix_interview_results_student_id'), table_name='interview_results')
    op.drop_table('interview_results')
    op.drop_index(op.f('ix_chat_history_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_student_id'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_quiz_results_id'), table_name='quiz_results')
    op.drop_index(op.f('ix_quiz_results_student_id'), table_name='quiz_results')
    op.drop_table('quiz_results')
    op.drop_table('leetcode_history')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_resume_analysis_v2_id'), table_name='resume_analysis_v2')
    op.drop_table('resume_analysis_v2')
    op.drop_index(op.f('ix_ai_memories_id'), table_name='ai_memories')
    op.drop_index(op.f('ix_ai_memories_session_id'), table_name='ai_memories')
    op.drop_table('ai_memories')
    op.drop_index(op.f('ix_ai_cache_id'), table_name='ai_cache')
    op.drop_index(op.f('ix_ai_cache_query'), table_name='ai_cache')
    op.drop_table('ai_cache')
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('company_jobs', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('company_jobs', 'employment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('company_jobs', 'experience_level',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_index(op.f('ix_company_jobs_company_id'), 'company_jobs', ['company_id'], unique=False)
    op.alter_column('company_profiles', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('company_profiles', 'verification_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('job_listings', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('job_listings', 'company',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('job_listings', 'location',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('job_listings', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('job_listings', 'skills',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('job_listings', 'salary',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('job_listings', 'job_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('job_listings', 'source',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('job_listings', 'url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('job_listings', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('profiles', sa.Column('dream_company', sa.String(length=150), nullable=True))
    op.add_column('profiles', sa.Column('study_hours_per_day', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('learning_style', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('experience_level', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('semester', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('branch', sa.String(length=100), nullable=True))
    op.alter_column('resume_analysis', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('resume_analysis', 'target_role',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('resume_analysis', 'match_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('resume_analysis', 'matched_skills',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('resume_analysis', 'missing_skills',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('resume_analysis', 'ai_feedback',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('resume_analysis', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_resume_analysis_student_id'), table_name='resume_analysis')
    op.create_foreign_key(None, 'resume_analysis', 'users', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resume_analysis', type_='foreignkey')
    op.create_index(op.f('ix_resume_analysis_student_id'), 'resume_analysis', ['student_id'], unique=False)
    op.alter_column('resume_analysis', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('resume_analysis', 'ai_feedback',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('resume_analysis', 'missing_skills',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('resume_analysis', 'matched_skills',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('resume_analysis', 'match_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('resume_analysis', 'target_role',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('resume_analysis', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('profiles', 'branch')
    op.drop_column('profiles', 'semester')
    op.drop_column('profiles', 'experience_level')
    op.drop_column('profiles', 'learning_style')
    op.drop_column('profiles', 'study_hours_per_day')
    op.drop_column('profiles', 'dream_company')
    op.alter_column('job_listings', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('job_listings', 'url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('job_listings', 'source',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('job_listings', 'job_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('job_listings', 'salary',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('job_listings', 'skills',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('job_listings', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('job_listings', 'location',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('job_listings', 'company',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('job_listings', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('company_profiles', 'verification_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('company_profiles', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_company_jobs_company_id'), table_name='company_jobs')
    op.alter_column('company_jobs', 'experience_level',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('company_jobs', 'employment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('company_jobs', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_table('ai_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('query', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_cache_pkey'))
    )
    op.create_index(op.f('ix_ai_cache_query'), 'ai_cache', ['query'], unique=True)
    op.create_index(op.f('ix_ai_cache_id'), 'ai_cache', ['id'], unique=False)
    op.create_table('ai_memories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('history_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ai_memories_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_memories_pkey'))
    )
    op.create_index(op.f('ix_ai_memories_session_id'), 'ai_memories', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_memories_id'), 'ai_memories', ['id'], unique=False)
    op.create_table('resume_analysis_v2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_role', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('ats_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parsed_profile', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('skills', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('experience', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('education', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('grammar_analysis', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('keyword_analysis', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('company_match', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('improvement_suggestions', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('resume_analysis_v2_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('resume_analysis_v2_pkey'))
    )
    op.create_index(op.f('ix_resume_analysis_v2_id'), 'resume_analysis_v2', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('goal', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('skills', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quiz_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('students_pkey'))
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_table('leetcode_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('track', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('topic', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('problem', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hint_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('leetcode_history_pkey'))
    )
    op.create_table('quiz_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topic', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('quiz_results_pkey'))
    )
    op.create_index(op.f('ix_quiz_results_student_id'), 'quiz_results', ['student_id'], unique=False)
    op.create_index(op.f('ix_quiz_results_id'), 'quiz_results', ['id'], unique=False)
    op.create_table('chat_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_history_pkey'))
    )
    op.create_index(op.f('ix_chat_history_student_id'), 'chat_history', ['student_id'], unique=False)
    op.create_index(op.f('ix_chat_history_id'), 'chat_history', ['id'], unique=False)
    op.create_table('interview_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('overall_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_results_pkey'))
    )
    op.create_index(op.f('ix_interview_results_student_id'), 'interview_results', ['student_id'], unique=False)
    op.create_index(op.f('ix_interview_results_id'), 'interview_results', ['id'], unique=False)
    # ### end Alembic commands ###
